### ISSUE TITLE
DAQCascade512II_Main.vi_Handel messages.vi

### ISSUE THREAD

**Issue by aqeisari** [marcelvanthoff/Giorgio#59]
It shows an error saying "This VI doesn't match other VIs in the method, Connector Pane Terminal(s) are different". Any solution?

**Comment by marcelvanthoff** [comment]
There are a few reasons why this error occurs:

- Either the parent method is Dynamic, the child is Static Dispatch Template
- The Child has a connector input / output missing or extra
- The connector inputs and outputs are correct, however one input is of the type "Required", while for example the other is "Optional"

Thus check the connector pane terminals for the child and compare it with the parent.

**Comment by aqeisari** [comment]
Thanks Marcel. Connector pane terminal mismatch in 2x2 binning.vi with parent method is solved
