### ISSUE TITLE
DAQCascade512II_proceed.vi_"is started?"

### ISSUE THREAD

**Issue by aqeisari** [marcelvanthoff/Giorgio#60]
After the first "1 second acquisition" loop, the camera sends stop message due to the false flag of "Is started.vi". Does anybody have an idea what can be the problem?

**Comment by marcelvanthoff** [comment]
Is the Parent method called before or after your code in the Start method?
The parent (Murmex) sets the "Is started" flag in the Start method, so read this flag only after execution of the parent. Does that make sense for you?

**Comment by aqeisari** [comment]
yes, it is solved.
